Consent Packages For Bylaw Changes
OWASP/www-policy pull request #35
Opened 2021-03-16 16:44 UTC by kerberosmansour

Updated bylaws for:
1) Grammar/typos
2) Two sections which included the words "Except as otherwise provided in these Bylaws" to avoid conflicting clauses SECTION 3.06 Quorum & SECTION 3.08 Manner of Acting
3) Gender neutal changes - replaced all "He/She" and "He or She" with "They"

2021-03-16 20:53 UTC, kingthorin requested changes

2021-03-16 20:53 UTC, kingthorin commented on legal/bylaws.md
> +- Fiduciary responsibilities: They shall, in general, supervise and control all of the business and affairs of the Foundation. They will monitor financial planning and financial reports they or he ma
```suggestion
- Fiduciary responsibilities: They shall, in general, supervise and control all of the business and affairs of the Foundation. They will monitor financial planning and financial reports they may sign, with the Secretary or any other proper officer of the Foundation thereunto authorized by the Board of Directors, any deeds, mortgages, bonds, contracts, or other instruments which the Board of Directors has authorized to be executed, except in cases where the signing and execution thereof shall be expressly delegated by the Board of Directors or by these Bylaws to some other officer or agent of the Foundation, or shall be required by law to be otherwise signed or executed;
```

2021-03-16 20:53 UTC, kingthorin commented on legal/bylaws.md
> +- Leadership and Direction: provides leadership to the Board of Directors with regards to policy setting and strategic planning. They helps guide and mediate board actions with respect to organizatio
```suggestion
- Leadership and Direction: provides leadership to the Board of Directors with regards to policy setting and strategic planning. They help guide and mediate board actions with respect to organizational priorities and governance concerns, and in general shall perform all duties incident to the office of Chairman of the Board subject to the control of the Board of Directors.
```

2021-03-16 20:53 UTC, kingthorin commented on legal/bylaws.md
> +- Organizational Responsibilities: They plays a leading role in fundraising activities, formally evaluate the performance of the Foundation Director and informally evaluate the effectiveness of the b
```suggestion
- Organizational Responsibilities: They play a leading role in fundraising activities, formally evaluate the performance of the Foundation Director and informally evaluate the effectiveness of the board members. An annual, overall evaluation of the performance of the organization in achieving its mission will be accomplished. They shall, when present, preside at all meetings of the Board of Directors, unless otherwise delegated, and such other duties as may be prescribed by the Board of Directors from time to time.
```

2021-03-16 20:53 UTC, kingthorin commented on legal/bylaws.md
> +1. Every Officer, Board Member, and employee of the Foundation shall be indemnified by the Foundation against all expenses and liabilities, including counsel fees, reasonably incurred by or imposed u
```suggestion
1. Every Officer, Board Member, and employee of the Foundation shall be indemnified by the Foundation against all expenses and liabilities, including counsel fees, reasonably incurred by or imposed upon him or her in connection with any proceeding to which they may be made a party, or in which they may become involved, by reason of being or having been a director, officer, employee or agent of the Foundation or is or was serving at the request of the Foundation as a director, officer, employee or agent of the Foundation, partnership, joint venture, trust or enterprise, or any settlement thereof, whether or not he is a director, officer, employee or agent at the time such expenses are incurred, except in such cases wherein the director, officer, employee or agent is adjudged guilty of willful misfeasance or malfeasance in the performance of their duties; provided that in the event of a settlement the indemnification herein shall apply only when the Board of Directors approves such settlement and reimbursement as being in the best interests of the Foundation.
```

"his or her" -> "their"

2021-03-17 00:56 UTC, kingthorin commented
Ping @kerberosmansour 😀

2021-03-22 11:00 UTC, kerberosmansour commented on legal/bylaws.md
> +- Fiduciary responsibilities: They shall, in general, supervise and control all of the business and affairs of the Foundation. They will monitor financial planning and financial reports they or he ma
Thanks!

2021-03-23 16:29 UTC, kingthorin commented
This should be closed in favor of #36?

2021-03-23 16:32 UTC, kingthorin commented on legal/bylaws.md
> +1. Every Officer, Board Member, and employee of the Foundation shall be indemnified by the Foundation against all expenses and liabilities, including counsel fees, reasonably incurred by or imposed u
```suggestion
1. Every Officer, Board Member, and employee of the Foundation shall be indemnified by the Foundation against all expenses and liabilities, including counsel fees, reasonably incurred by or imposed upon them in connection with any proceeding to which they may be made a party, or in which they may become involved, by reason of being or having been a director, officer, employee or agent of the Foundation or is or was serving at the request of the Foundation as a director, officer, employee or agent of the Foundation, partnership, joint venture, trust or enterprise, or any settlement thereof, whether or not he is a director, officer, employee or agent at the time such expenses are incurred, except in such cases wherein the director, officer, employee or agent is adjudged guilty of willful misfeasance or malfeasance in the performance of their duties; provided that in the event of a settlement the indemnification herein shall apply only when the Board of Directors approves such settlement and reimbursement as being in the best interests of the Foundation.
```

him or her -> them

2021-03-23 16:33 UTC, kingthorin commented
I'm unclear what's going on with #35/#36 so I've marked them both up, sorry I missed this occurrence earlier.

2021-03-23 20:30 UTC, vanderaj commented
@kerberosmansour This PR is not linked in the Board vote today. Can you let me know if this is also to be merged?

2021-03-23 20:34 UTC, kerberosmansour commented
No, I made another PR to incorporate the feedback (and minor additions) -
please use the PR listed on the BoD meeting page please

On Tue, 23 Mar 2021 at 20:30, Andrew van der Stock ***@***.***>
wrote:

> @kerberosmansour <https://github.com/kerberosmansour> This PR is not
> linked in the Board vote today. Can you let me know if this is also to be
> merged?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/OWASP/www-policy/pull/35#issuecomment-805230156>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ADGPVQTVH4MA42TBL2EF2ATTFD263ANCNFSM4ZI5HMZQ>
> .
>

2021-03-23 21:30 UTC, vanderaj commented
PR #36 has been merged earlier this afternoon. Therefore, I'm going to close this one. If that's not right, please re-open.

2021-03-23 21:30 UTC, closed without merging